#!/usr/bin/env bash

log_file="/home/truthserum/Alx/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/apache-access.log"

# Use awk to extract and format the information
awk '{print $1, $9}' "${log_file}"
